controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

homepage:
    path: /
    controller: App\Controller\HomeController::getPage


houses:
    path: /antwerp/houses
    controller: App\Controller\HouseController::getPage